expose_php=0
display_errors=0
display_startup_errors=0
log_errors=1
error_log=/proc/self/fd/2
memory_limit=256M
max_execution_time=60
max_input_time=60
max_input_vars=2000
post_max_size=32M
upload_max_filesize=32M
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_secure=1
session.cookie_samesite=Lax
allow_url_fopen=0
allow_url_include=0
